# === Load .env (generated by `make configure`) if present ===
# Values from .env apply everywhere below, and can be overridden on the
# command line: make deploy APP_NAME=my-api
ifneq (,$(wildcard .env))
include .env
export
endif

# === Variables - defaults used when not in .env ===
APP_NAME        ?= myapp
NAMESPACE       ?= $(APP_NAME)
ENVIRONMENT     ?= production
IMAGE           ?= $(APP_NAME):latest
REPLICAS        ?= 2
APP_PORT        ?= 3000
SERVICE_PORT    ?= 80
SERVICE_TYPE    ?= ClusterIP
INGRESS_HOST    ?=
INGRESS_CLASS   ?= nginx
INGRESS_PATH    ?= /
HEALTHCHECK_PATH ?= /health
MEMORY_REQUEST  ?= 128Mi
CPU_REQUEST     ?= 100m
MEMORY_LIMIT    ?= 256Mi
CPU_LIMIT       ?= 500m

export APP_NAME NAMESPACE ENVIRONMENT IMAGE REPLICAS APP_PORT SERVICE_PORT
export SERVICE_TYPE INGRESS_HOST INGRESS_CLASS INGRESS_PATH HEALTHCHECK_PATH
export MEMORY_REQUEST CPU_REQUEST MEMORY_LIMIT CPU_LIMIT

# === Targets ===

.PHONY: help configure validate preview deploy undeploy status logs envfile pod compose compose-preview

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

configure: ## Ask you a few questions, write .env, pick the right k8s files
	@python3 scripts/configure.py

validate: ## Check your configuration (also runs in CI)
	@python3 scripts/configure.py --check

preview: ## Print the exact Kubernetes manifests that will be deployed
	@python3 scripts/deploy.py --preview

deploy: ## Deploy to Kubernetes (uses .env / environment values)
	@python3 scripts/deploy.py --yes

undeploy: ## Delete the entire namespace (tears down everything)
	@kubectl delete namespace $(NAMESPACE) --ignore-not-found

status: ## Show deployment status
	@kubectl get all -n $(NAMESPACE)

logs: ## Tail logs from running pods
	@kubectl logs -n $(NAMESPACE) -l app=$(APP_NAME) --tail=100 -f

envfile: ## Regenerate .env.example from current values
	@{ \
		echo "# Kubernetes deployment configuration"; \
		echo "# Normally generated for you by: make configure"; \
		echo ""; \
		echo "APP_NAME=$(APP_NAME)"; \
		echo "NAMESPACE=$(NAMESPACE)"; \
		echo "ENVIRONMENT=$(ENVIRONMENT)"; \
		echo "IMAGE=$(IMAGE)"; \
		echo ""; \
		echo "REPLICAS=$(REPLICAS)"; \
		echo "APP_PORT=$(APP_PORT)"; \
		echo "SERVICE_PORT=$(SERVICE_PORT)"; \
		echo "SERVICE_TYPE=$(SERVICE_TYPE)"; \
		echo ""; \
		echo "# Only if you want a public domain (otherwise leave empty):"; \
		echo "INGRESS_HOST=$(INGRESS_HOST)"; \
		echo "INGRESS_CLASS=$(INGRESS_CLASS)"; \
		echo "INGRESS_PATH=$(INGRESS_PATH)"; \
		echo ""; \
		echo "HEALTHCHECK_PATH=$(HEALTHCHECK_PATH)"; \
		echo ""; \
		echo "MEMORY_REQUEST=$(MEMORY_REQUEST)"; \
		echo "CPU_REQUEST=$(CPU_REQUEST)"; \
		echo "MEMORY_LIMIT=$(MEMORY_LIMIT)"; \
		echo "CPU_LIMIT=$(CPU_LIMIT)"; \
		echo ""; \
		echo "# Extra environment variables passed to your app, comma-separated:"; \
		echo "# EXTRA_ENV=API_URL=https://x,LOG_LEVEL=debug"; \
		echo "EXTRA_ENV="; \
	} > .env.example
	@echo "Created .env.example"

# === Docker Compose bridge ===

compose: ## Generate K8s manifests from docker-compose.yml
	@python3 scripts/compose-to-k8s.py

compose-preview: ## Run docker-compose config (validate your compose file)
	@docker-compose config

# === Quick pod for testing ===

pod: ## Run a standalone test pod (no service, no deployment)
	@python3 scripts/deploy.py --pod
