apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-config
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    env: ${ENVIRONMENT}
data:
  APP_NAME: "${APP_NAME}"
  APP_ENV: "${ENVIRONMENT}"
  APP_PORT: "${APP_PORT}"
